---

- debug:
    msg: >
      osfamily{{ ':'}}{{ ansible_os_family }}
      , distribution{{ ':'}}{{ ansible_distribution }}
      , release{{ ':'}}{{ ansible_distribution_release }}
      , version{{ ':'}}{{ ansible_distribution_major_version }}({{ ansible_distribution_version }})
      , pkg{{ ':'}}{{ ansible_pkg_mgr}}

- include_vars: '{{ item }}'
  with_first_found:
  - files:
      - '{{ ansible_os_family }}.yml'
      - 'default.yml'
    paths: '{{ role_path }}/vars/os'

# - name: Update repositories cache and upgrade
#   apt:
#     update_cache: yes
#     upgrade: dist
#   ignore_errors: yes
