---

- name: Create temporary deb file directory
  tempfile: state=directory
  register: deb_temp

- set_fact:
    temp_ic:
      name: docker
      url: "{{ docker_packages[ansible_distribution ][ansible_distribution_release].url }}"
      file: "{{ docker_packages[ansible_distribution ][ansible_distribution_release].file }}"

- name: Download '{{ temp_ic.file }}'
  cached_get_url:
    cached: "{{ resource_cache }}/{{ temp_ic.file }}"
    url: "{{ temp_ic.url }}"
    dest: '{{ deb_temp.path }}/{{ temp_ic.file }}'

- name: Install a .deb package
  apt:
    deb: '{{ deb_temp.path}}/{{ temp_ic.file }}'
